JobsV1/Models/InvCarGateControl.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCarGateControl
    {
        public int Id { get; set; }
        public int InvItemId { get; set; }
        public int In_Out_flag { get; set; }
        public string Odometer { get; set; }
        public System.DateTime dtControl { get; set; }
        public string Remarks { get; set; }
        public string Driver { get; set; }
        public string Inspector { get; set; }
    
        public virtual InvItem InvItem { get; set; }
    }
}

JobsV1/Controllers/InvCarGateControlsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobsV1.Models;

namespace JobsV1.Controllers
{
    public class InvCarGateControlsController : Controller
    {
        private JobDBContainer db = new JobDBContainer();

        // GET: InvCarGateControls
        public ActionResult Index()
        {
            var invCarGateControls = db.InvCarGateControls.Include(i => i.InvItem).OrderByDescending(c=>c.dtControl);

            //get records past their next odometer & schedule change
            //odometer
            List<InvCarRecord> priority = new List<InvCarRecord>();

            foreach (var carList in db.InvItems.Where(s => s.ViewLabel == "UNIT").ToList())
            {
                //latest next odometer of the car
                var priorityRecords = db.InvCarRecords.Include(i => i.InvCarRecordType).Include(i => i.InvItem)
                    .Where(c => c.InvItemId == carList.Id).OrderByDescending(s => s.NextOdometer).FirstOrDefault();

                priority.Add(priorityRecords);
            }

            ViewBag.priority = priority;
            
            return View(invCarGateControls.ToList());
        }

        // GET: InvCarGateControls/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvCarGateControl invCarGateControl = db.InvCarGateControls.Find(id);
            if (invCarGateControl == null)
            {
                return HttpNotFound();
            }
            return View(invCarGateControl);
        }

        // GET: InvCarGateControls/Create
        public ActionResult Create(int? control)
        {
            InvCarGateControl invcar = new InvCarGateControl();

            if (control == null)
            {
                invcar.In_Out_flag = 1; //gate out
            }
            else
            {
                invcar.In_Out_flag = (int)control;
            }
            
            invcar.dtControl = DateTime.Now;

            var invItems = db.InvItems.Where(s => s.ViewLabel == "UNIT").Select(
                    s => new SelectListItem
                    {
                        Value = s.Id.ToString(),
                        Text = s.ItemCode.ToString() + " - " + s.Description
                    }
                );
            ViewBag.recordType = invcar.In_Out_flag == 1 ? "Out" : "In";
            ViewBag.InvItemId = new SelectList(invItems, "Value", "Text");
            return View(invcar);
        }

        // POST: InvCarGateControls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,InvItemId,In_Out_flag,Odometer,dtControl,Remarks,Driver,Inspector")] InvCarGateControl invCarGateControl)
        {
            if (ModelState.IsValid)
            {
                db.InvCarGateControls.Add(invCarGateControl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.InvItemId = new SelectList(db.InvItems, "Id", "ItemCode", invCarGateControl.InvItemId);
            return View(invCarGateControl);
        }

        // GET: InvCarGateControls/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvCarGateControl invCarGateControl = db.InvCarGateControls.Find(id);
            if (invCarGateControl == null)
            {
                return HttpNotFound();
            }
            ViewBag.InvItemId = new SelectList(db.InvItems, "Id", "ItemCode", invCarGateControl.InvItemId);
            return View(invCarGateControl);
        }

        // POST: InvCarGateControls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,InvItemId,In_Out_flag,Odometer,dtControl,Remarks,Driver,Inspector")] InvCarGateControl invCarGateControl)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invCarGateControl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.InvItemId = new SelectList(db.InvItems, "Id", "ItemCode", invCarGateControl.InvItemId);
            return View(invCarGateControl);
        }

        // GET: InvCarGateControls/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvCarGateControl invCarGateControl = db.InvCarGateControls.Find(id);
            if (invCarGateControl == null)
            {
                return HttpNotFound();
            }
            return View(invCarGateControl);
        }

        // POST: InvCarGateControls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            InvCarGateControl invCarGateControl = db.InvCarGateControls.Find(id);
            db.InvCarGateControls.Remove(invCarGateControl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobsV1/Views/InvCarGateControls/Create.cshtml
@model JobsV1.Models.InvCarGateControl

@{
    ViewBag.Title = "Create";
}

<h2>Create Unit @ViewBag.recordType </h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InvCarGateControl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.InvItemId, "InvItemId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("InvItemId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InvItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.In_Out_flag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.In_Out_flag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.In_Out_flag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Odometer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Odometer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Odometer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtControl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtControl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtControl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Driver, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Driver, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Driver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Inspector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Inspector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Inspector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="~/Scripts/Job/CarGateControl.js"></script>
}

JobsV1/Views/InvCarGateControls/Delete.cshtml
@model JobsV1.Models.InvCarGateControl

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InvCarGateControl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.In_Out_flag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.In_Out_flag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Odometer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Odometer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtControl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtControl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Driver)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Driver)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inspector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inspector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvItem.ItemCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvItem.ItemCode)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JobsV1/Views/InvCarGateControls/Details.cshtml
@model JobsV1.Models.InvCarGateControl

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>InvCarGateControl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.In_Out_flag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.In_Out_flag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Odometer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Odometer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtControl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtControl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Driver)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Driver)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inspector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inspector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvItem.ItemCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvItem.ItemCode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JobsV1/Views/InvCarGateControls/Edit.cshtml
@model JobsV1.Models.InvCarGateControl

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InvCarGateControl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.InvItemId, "InvItemId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("InvItemId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InvItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.In_Out_flag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.In_Out_flag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.In_Out_flag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Odometer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Odometer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Odometer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtControl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtControl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtControl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Driver, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Driver, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Driver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Inspector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Inspector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Inspector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="~/Scripts/Job/CarGateControl.js"></script>
}

JobsV1/Views/InvCarGateControls/Index.cshtml
@model IEnumerable<JobsV1.Models.InvCarGateControl>

@{
    ViewBag.Title = "Index";
}

<h2>Gate Control Records</h2>

<p>
    @Html.ActionLink(" Vehicle  Out ", "Create", new { control = 1 }) |
    @Html.ActionLink(" Vehicle  In ", "Create", new { control = 2 })
</p>
<table class="table">
    <tr>
        <th>
            Vehicle
        </th>
        <th>
            Out
        </th>
        <th>
            In
        </th>
        <th>
            Odometer
        </th>
        <th>
            Driver
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.InvItem.ItemCode)
            -
            @Html.DisplayFor(modelItem => item.InvItem.Description)
        </td>

        @if (item.In_Out_flag == 1)
        { // out

            <td>
                @Html.DisplayFor(modelItem => item.dtControl)
            </td>
            <td>  - </td>
        }
        else
        {
            <td> - </td>
            <td>
                @Html.DisplayFor(modelItem => item.dtControl)
            </td>
        }

        <td>
            @String.Format("{0:n0}", int.Parse( item.Odometer))
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Driver)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Records", "Index", "InvCarGateControls",new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>


@foreach (var prio in ViewBag.priority as IEnumerable<JobsV1.Models.InvCarRecord>)
{
    //Odometer filter
    try
    {
        var currentOdo = int.Parse(@prio.InvItem.InvCarGateControls.OrderByDescending(s => s.dtControl).FirstOrDefault().Odometer);
        if (currentOdo > prio.NextOdometer)
        {
            <script type="text/javascript">
                alert('@prio.InvItem.ItemCode @prio.InvItem.Description is needed for @prio.InvCarRecordType.Description . @currentOdo of @prio.NextOdometer ');
            </script>
        }
        else
        {

            if (currentOdo + 1000 > prio.NextOdometer)
            {
                <script type="text/javascript">
                alert('@prio.InvItem.ItemCode @prio.InvItem.Description is needed for @prio.InvCarRecordType.Description . @currentOdo of @prio.NextOdometer ');
                </script>
            }

        }


    }
    catch (Exception e)
    { }

    //Date of last change filter
    try
    {
        if (DateTime.Compare(DateTime.Today, prio.NextSched) >= 0)
        {
            <script type="text/javascript">
                alert('@prio.InvItem.ItemCode @prio.InvItem.Description is needed for @prio.InvCarRecordType.Description . Scheduled change: @prio.NextSched ');
            </script>
        }
        else
        {

            if (DateTime.Compare(DateTime.Today.AddDays(10), prio.NextSched) >= 0)
            {
                <script type="text/javascript">
                alert('@prio.InvItem.ItemCode @prio.InvItem.Description is needed for @prio.InvCarRecordType.Description . Scheduled change: @prio.NextSched ');
                </script>
            }
        }

    }
    catch (Exception e)
    { }

}